id: P003165
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10582
  title: སྔགས་ཀྱི་བཀླག་ཐབས་བསྡུས་པ་དང་དེའི་འགྲེལ་པ་མཐོང་བ་དོན་གསལ།
  author: ''
  volumes:
    5f8c917f2f8c43e5b1c7f8febe6587fa:
      image_group_id: I1KG10585
      title: ''
      volume_number: 1
      total_pages: 40
