id: P003165
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 10:44:36.312180
source_metadata:
  id: bdr:W1KG10582
  title: སྔགས་ཀྱི་བཀླག་ཐབས་བསྡུས་པ་དང་དེའི་འགྲེལ་པ་མཐོང་བ་དོན་གསལ།
  author: ''
  volumes:
    5f8c917f2f8c43e5b1c7f8febe6587fa:
      image_group_id: I1KG10585
      title: ''
      volume_number: 1
      total_pages: 40
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
