id: I05CCEFC0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:38:22+00:00'
last_modified: '2022-06-07T18:01:42.580588+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10582
  title: སྔགས་ཀྱི་བཀླག་ཐབས་བསྡུས་པ་དང་དེའི་འགྲེལ་པ་མཐོང་བ་དོན་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E4A2:
      image_group_id: I1KG10585
      title: ''
      total_pages: 40
      order: 1
      base_file: E4A2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
